version: '{build}'
image: Ubuntu
install:
- sh: git submodule update --init --recursive
- sh: sudo apt-get update
- sh: sudo apt-get install -y rpm
build_script:
- sh: mkdir build
- sh: cd build
- sh: cmake .. -DCMAKE_BUILD_TYPE=Release -DFOREST_BUILD_TESTS=ON
- sh: make -j2
- sh: ctest
- sh: cpack -G DEB
- sh: cpack -G RPM
artifacts:
- path: build/*.deb
- path: build/*.rpm
deploy:
- provider: GitHub
  auth_token:
    secure: AtDbVKW82I4iP+STKQ9ZEHEjzZZDYN/GqxC4mPfejyDyKs8Nozo3gYEHVLJUaZup
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
