version: '{build}'
image:
- Ubuntu
configuration:
- Release
install:
- sh: sudo apt-get update
- sh: sudo update-alternatives --set gcc /usr/bin/gcc-8
before_build:
- sh: git submodule update --init --recursive
- sh: mkdir build
- sh: cd build
- sh: cmake .. -DFOREST_BUILD_TESTS=ON
build_script:
- sh: cmake --build .
test_script:
- sh: ctest --output-on-failure
after_test:
- sh: cpack -G DEB
artifacts:
- path: build/*.deb
deploy:
- provider: GitHub
  auth_token:
    secure: AtDbVKW82I4iP+STKQ9ZEHEjzZZDYN/GqxC4mPfejyDyKs8Nozo3gYEHVLJUaZup
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
