version: '{build}'
image: Ubuntu
install:
- sh: git submodule update --init --recursive
build_script:
- sh: >-
    mkdir build

    cd build

    cmake .. -DBUILD_TESTS=ON

    make

    cd test

    ctest
artifacts:
- path: include/forest/AVLTree.hpp
  name: AVLTree.hpp
- path: include/forest/BinarySearchTree.hpp
  name: BinarySearchTree.hpp
- path: include/forest/KDTree.hpp
  name: KDTree.hpp
- path: include/forest/QuadTree.hpp
  name: QuadTree.hpp
- path: include/forest/RedBlackTree.hpp
  name: RedBlackTree.hpp
- path: include/forest/SplayTree.hpp
  name: SplayTree.hpp
deploy:
- provider: GitHub
  auth_token:
    secure: AtDbVKW82I4iP+STKQ9ZEHEjzZZDYN/GqxC4mPfejyDyKs8Nozo3gYEHVLJUaZup
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
